name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: trading_duel_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Setup Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/v1.16.0/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Setup Anchor CLI
      run: |
        npm install -g @coral-xyz/anchor-cli@0.28.0

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Generate Prisma client
      run: npx prisma generate
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/trading_duel_test

    - name: Build Anchor program
      run: anchor build

    - name: Run Anchor tests
      run: anchor test --skip-local-validator
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/trading_duel_test

    - name: Run API tests
      run: |
        cd services/api
        npm test
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/trading_duel_test
        REDIS_URL: redis://localhost:6379

    - name: Run Oracle tests
      run: |
        cd services/oracle
        npm test
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/trading_duel_test

    - name: Check TypeScript compilation
      run: |
        yarn tsc --noEmit

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run security audit
      run: |
        yarn audit --level moderate

    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD 